### ISSUE TITLE
Research and add SEO to ensure relaxio shows on first page of search results for "relaxio"

### ISSUE THREAD

**Issue by docsmage** [voiceofrae/RelaxIO#65]

**Comment by audreytoskin** [comment]
For me, Google shows the Play Store listings of some Android app developer going by the name Relaxio.

However, [you *are* number one on DuckDuckGo](https://duckduckgo.com/?q=%22relaxio%22&t=ffab&ia=web). So your SEO can't be too terrible.

**Comment by audreytoskin** [comment]
Google and other search engines like to say that, at bottom, their sorting algorithms are just trying to find the sorts of web pages that users will want to see — because the page is interesting, useful, whatever — and that you should therefore focus on just creating compelling content and apps. Beyond this, most of the SEO techniques I know are basically just about making sure your page explains itself well and is well formatted (unless you're trying to build a clickbait farm 😈 ).

* [ ] [Semantic markup](https://en.wikipedia.org/wiki/Semantic_HTML) --- this applies somewhat more so to articles than apps, but probably you'd want to check on some basic things, like:
    * actually using `<p>` elements for paragraphs, `<blockquote>` for blockquotes, `<header>` and `<footer>` for headers and footers, `<nav>`, `<main>`, and so on, rather than just dumping *everything* into a `<div>`.
    * headings should be marked up as headings instead of simply styled with larger `font-size`.
    * also, the different uses of bold and italics in text mean different things, so you should be using different tags to mark them up: `<em>` for emphasis, `<cite>` for titles of a work, `<strong>` for important phrases you don't want the user to skip or misread... [`<i>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/i) and [`<b>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/b) aren't actually deprecated, but their intended use cases are relatively limited.
* [ ] Put a descriptive title in your `<h1>` and `<title>` tags, and write a short and sweet [`<meta>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) description tag for every page. `<meta>` tags containing a list of keywords are just about universally ignored, because it's too easy to abuse, but a short description can still be good.
* [ ] [OpenGraph](http://opengraphprotocol.org/) `<meta>` tags will help give you a nice-looking preview when people share a link to Relaxio.
* [ ] Backlinks also help, so try posting about Relaxio on Twitter, Reddit, wherever. If you really wanted to make a big push, you could also ask friends to re-share and comment, and submit to blogs and stuff, but that's starting to turn into social engineering rather than SEO.
* [ ] Keyword optimization (also pejoratively called "keyword *stuffing*") is where you try to use a keyword or keyphrase as many times as possible to help make sure your site appears higher up for searches for that word or phrase. I wouldn't bother with this except to make sure the `<meta>` description and About page use relevant language --- probably you ought to mention something about "white noise", "soothing sounds", "relaxation", and/or possibly "ASMR", or whatever phrasing you think most appropriate --- but anything much beyond that veers toward keyword abuse, a technique commonly used in spammy clickbait sites, and you don't want search engines to flag you as spam...

**Comment by docsmage** [comment]
This project is no longer maintained enough for this to be relevant
